export const jobInputs = [
  {
    id: 0,
    name: "company",
    type: "text",
    placeholder: "Enter your company name ",
    label: "Company Name",
  },
  {
    id: 1,
    name: "logoUrl",
    type: "text",
    placeholder: "Enter the Logo link",
    label: "Add logo URL",
  },
  {
    id: 2,
    name: "title",
    type: "text",
    placeholder: "Enter Job Position",
    label: "Job position",
  },
  {
    id: 3,
    name: "monthlySalary",
    type: "number",
    placeholder: "Enter Amount in Rupees",
    label: "Monthly Salary",
  },
  {
    id: 4,
    name: "duration",
    type: "number",
    placeholder: "Enter Duration in Months",
    label: "Duration",
  },
  {
    id: 5,
    name: "jobType",
    type: "select",
    label: "Job Type",
    options: ["Full Time", "Part Time", "Contract", "Internship"],
  },
  {
    id: 6,
    name: "remoteOffice",
    type: "select",
    label: "Remote/Office",
    options: ["Remote", "Office", "Hybrid"],
  },
  {
    id: 7,
    name: "location",
    type: "text",
    placeholder: "Enter Location",
    label: "Location",
  },
];
